export const ExpenseCategoriesList = [
  "expense",
  "food and supermarkets",
  "home",
  "transport",
  "clothes and shoes",
  "health",
  "sport",
  "cafe and restaurants",
  "automobile",
  "taxi",
  "pets",
  "children",
  "beauty",
  "travel",
  "telecom",
  "internet",
  "entertainment",
  "mobile phone",
  "technology",
  "other",
];

export const IncomeCategoriesList = [
  "income",
  "salary",
  "business",
  "part-time job",
  "other",
];
